### ISSUE TITLE
svgo no longer requires types

### ISSUE THREAD

**Issue by bheston** [r3dDoX/vite-plugin-svgo#1]
It looks like as of `svgo` 3.0.0 they have built in types and no longer require `@types/svgo` which has been deprecated.

I haven't seen this issue before, but in a particular `tsconfig` setup within workspaces I'm getting an error regarding the existence of the placeholder types:

```
error TS2688: Cannot find type definition file for 'svgo'.
  The file is in the program because:
    Entry point for implicit type library 'svgo'
```

Please remove `@types/svgo` from the dependencies.

**Comment by r3dDoX** [comment]
Hello @bheston 
Sorry for being so late, I missed the Github notification. I removed the dependency and just released v1.3.0
